# Gitleaks configuration for SoundHash
# This configuration defines custom rules and allowlists for secret scanning

title = "SoundHash Gitleaks Configuration"

# Extend the default Gitleaks configuration
[extend]
useDefault = true

# Custom rules for SoundHash-specific patterns
[[rules]]
id = "youtube-api-key"
description = "YouTube API Key"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
tags = ["api", "youtube", "key"]

[[rules]]
id = "generic-api-key-header"
description = "API Key in header or config"
regex = '''(?i)(api[_-]?key|apikey)\s*[:=]\s*['"]?[a-zA-Z0-9_\-]{20,}['"]?'''
tags = ["api", "key"]

[[rules]]
id = "twitter-bearer-token"
description = "Twitter Bearer Token"
regex = '''(?i)bearer\s+[a-zA-Z0-9_\-\.=]{100,}'''
tags = ["twitter", "bearer", "token"]

[[rules]]
id = "reddit-secret"
description = "Reddit Client Secret"
regex = '''(?i)reddit[_-]?client[_-]?secret\s*[:=]\s*['"]?[a-zA-Z0-9_\-]{20,}['"]?'''
tags = ["reddit", "secret"]

# Allowlist for false positives and documentation
[allowlist]
description = "Allowlisted files and patterns"

# Allow example files and documentation
paths = [
  '''.env.example''',
  '''README.md''',
  '''INSTALL.md''',
  '''AUTH_SETUP.md''',
  '''YOUTUBE_OAUTH_SETUP.md''',
  '''YOUTUBE_ACCESS_STATUS.md''',
  '''ROADMAP.md''',
  '''ARCHITECTURE.md''',
]

# Allow placeholder values in documentation and examples
regexes = [
  '''your_api_key_here''',
  '''your_client_id_here''',
  '''your_client_secret_here''',
  '''your_access_token_here''',
  '''your_password''',
  '''your_token_here''',
  '''example\.com''',
  '''localhost''',
  '''soundhash_password123''',  # Example password in .env.example
]

# Stop words for reducing false positives
stopwords = [
  "example",
  "placeholder",
  "your_",
  "test_",
  "sample_",
  "dummy",
  "fake",
]
