blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/onnwee/soundhash/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Contributing Guide
    url: https://github.com/onnwee/soundhash/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to SoundHash
